substitutions:
  device_name: bedroom-climate
  friendly_name: "Bedroom Climate"
  board: esp32dev
  i2c_sda_pin: GPIO21
  i2c_scl_pin: GPIO22

packages:
  base: !include ../common/base.yaml
  wifi: !include ../common/wifi.yaml
  sensor_bme280: !include ../common/sensors/bme280.yaml

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    id: device_status

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    id: wifi_signal_sensor
    update_interval: 60s

  - platform: uptime
    name: "${friendly_name} Uptime"
    id: uptime_sensor

button:
  - platform: restart
    name: "${friendly_name} Restart"
    id: restart_button
