substitutions:
  device_name: garage-door-controller
  friendly_name: "Garage Door Controller"
  board: esp32dev
  relay_pin: GPIO23
  sensor_pin: GPIO18

packages:
  base: !include ../common/base.yaml
  wifi: !include ../common/wifi.yaml

switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    id: garage_relay
    pin: ${relay_pin}
    icon: "mdi:garage"

binary_sensor:
  - platform: gpio
    name: "${friendly_name} Door Sensor"
    id: door_sensor
    pin:
      number: ${sensor_pin}
      mode:
        input: true
        pullup: true
      inverted: true
    device_class: garage_door

  - platform: status
    name: "${friendly_name} Status"
    id: device_status

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    id: wifi_signal_sensor
    update_interval: 60s

  - platform: uptime
    name: "${friendly_name} Uptime"
    id: uptime_sensor

button:
  - platform: restart
    name: "${friendly_name} Restart"
    id: restart_button
